# Generated by Django 2.2.10 on 2021-09-13 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mapel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_guru', models.CharField(max_length=50)),
                ('pelajaran', models.CharField(max_length=20)),
                ('jam_pelajaran', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'mapel',
            },
        ),
    ]
